---
# tasks file for alert-rules
- name: Criar diretório /mnt/volumes/observabilidade/prod/ se não existir
  file:
    path: /mnt/volumes/observabilidade/prod/alert-rules
    state: directory
    owner: infra
    group: infra
    mode: '0755'
  ignore_errors: yes

- name: Copiar o arquivo docker-compose.yml para a VM da telemetria
  template:
    src: templates/alert-rules.j2
    dest: /mnt/volumes/observabilidade/prod/alert-rules/alert-rules.yml
    owner: infra
    group: infra
    mode: '0644'