---
# tasks file for grafana-datasource
- name: Criar diretório /mnt/volumes/observabilidade/prod/ se não existir
  file:
    path: /mnt/volumes/observabilidade/prod/configs/grafana
    state: directory
    owner: infra
    group: infra
    mode: '0755'
  ignore_errors: yes

- name: Copiar o arquivo docker-compose.yml para a VM da telemetria
  template:
    src: templates/grafana-datasource.j2
    dest: /mnt/volumes/observabilidade/prod/configs/grafana/datasource.yml
    owner: infra
    group: infra
    mode: '0644'