---
# tasks file for tempo-local
- name: Criar diretório /mnt/volumes/observabilidade/prod/tempo se não existir
  file:
    path: /mnt/volumes/observabilidade/prod/tempo
    state: directory
    owner: infra
    group: infra
    mode: '0755'
  ignore_errors: yes
  
- name: Copiar o arquivo docker-compose.yml para a VM da telemetria
  template:
    src: tempo-local.j2
    dest: /mnt/volumes/observabilidade/prod/tempo/tempo-local.yml
    owner: infra
    group: infra
    mode: '0644'
