global:
  resolve_timeout: 1m

route:
  group_by: ['alert', 'job']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m # intervalo de tempo para o reenvio de um novo alerta.
  receiver: 'webhook'


receivers:
  - name: 'webhook'
    webhook_configs:
    - url: 'https://discord.com/api/webhooks/1346514049608843264/FTnbzFyLTUZjcRTQEgl0UTZfBqAJqw99S5gTdmnrcIAGSvYjH-4MuV_N6hFS1eJxzbZs'
      send_resolved: true # envia mensagem para o webhook quando o problema no serviço for resolvido.

templates:
  - '/etc/alertmanager/template/*.tmpl'
