auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  wal:
    enabled: true
    dir: /tmp/wal
  chunk_idle_period: 5m
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 48h
    resync_interval: 5s

  aws:
    s3: s3://LgaZzKq80GgKdjIIN7Il:qbLajExJ1cgejIoFh1svrrpjUknEbFJScKw2HwPF@10.10.106.46:9000/loki.storage
    s3forcepathstyle: true

compactor:
  working_directory: /loki/compactor
  delete_request_store: s3

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false
