receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  attributes:
    actions:
      - key: route
        from_attribute: body.route.name
        action: insert
      - key: workspace_name
        from_attribute: body.workspace_name
        action: insert
      - key: status
        from_attribute: body.response.status
        action: insert
      - key: service_name
        from_attribute: resource["service.name"]
        action: insert
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [attributes]
      exporters: [loki]
