---
- name: Configura a VM
  hosts: observabilidade
  become: yes
  roles:
    - vm_disk_expand
    - node_exporter
    - docker_engine_install
    - ../roles/prometheus
    - ../roles/blackbox-exporter
    - ../roles/otel-collector
    - ../roles/grafana-datasource
    - ../roles/loki-config
    - ../roles/tempo-local
    - ../roles/promtail-config
    - ../roles/alertmanager
    - ../roles/alert-rules
    - ../roles/install-docker
    - ../roles/compose-observabilidade
