---
# tasks file for docker
- name: Uninstall conflicting packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    force: yes

- name: Install required packages for Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create Docker keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository using shell
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt cache after adding Docker repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Ensure Docker is running and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Install Loki Docker logging plugin
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver:latest
    alias: loki
    state: present
  become: yes

- name: Enable the plugin
  community.docker.docker_plugin:
    plugin_name: loki
    state: enable

- name: Daemon JSON configuration
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "1g",
          "max-file": "3",
          "compress": "true"
        }
      }
  become: yes

- name: Enable usermod for Docker
  ansible.builtin.shell: usermod -aG docker "{{ ansible_user }}"
  become: yes

- name: Create a new group for Docker
  ansible.builtin.group:
    name: docker
    state: present

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
